name: 'Install software'
description: 'Greet someone'
inputs:
  cache-name:  # id of input
    description: 'Name to generate the full cache name'
    required: true
    default: 'cache-software-basis'
  filesForHash:
    description: 'List of files to be used for cache hash generation'
    required: true
    default: |
      '**/requirements*.txt'
  run_additional:
    description: "path to additional shell script to source"
  cache_paths:
    description: "paths to include in the caching"
    required: true
    default: |
      /home/runner/work/columnflow/columnflow/data/software/conda
      /home/runner/work/columnflow/columnflow/data/software/venvs/cf_*

runs:
  using: "composite"
  steps:
    - name: Checkout ⬇️
      uses: actions/checkout@master
      with:
        persist-credentials: false
        submodules: recursive

    - name: Setup python 🐍
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies ☕️
      id: install_cache
      uses: actions/cache@v3
      env:
        cache-name: ${{ inputs.cache-name }}
      with:
        path: |
          ${{ inputs.cache_paths }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(inputs.filesForHash) }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - if: ${{ steps.cache-software-basis.outputs.cache-hit != 'true' }}
      name: Install software stack
      continue-on-error: true
      run: |
        source setup.sh ""
      shell: bash
    - if: ${{ inputs.run_additional }}
      name: Install additional software
      run: |
        source setup.sh ""
        source ${{ inputs.run_additional }}
      shell: bash