name: 'Install software'
description: 'Greet someone'
inputs:
  cache-name:  # id of input
    description: 'Name to generate the full cache name'
    required: true
    default: 'cache-software-basis'
  filesForHash:
    description: 'List of files to be used for cache hash generation'
    required: true
    default: |
      '**/requirements*.txt'
      '**/sandboxes/cf_prod.sh'

runs:
  using: "composite"
  steps:
    - name: Checkout ⬇️
      uses: actions/checkout@master
      with:
        persist-credentials: false
        submodules: recursive

    - name: Setup python 🐍
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies ☕️
      id: install_cache
      uses: actions/cache@v3
      env:
        cache-name: ${{ inputs.cache-name }}
      with:
        path: |
          /home/runner/work/columnflow/columnflow/data/software/venvs
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles( ${{ inputs.filesForHash }} ) }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - if: ${{ steps.cache-software-basis.outputs.cache-hit != 'true' }}
      name: Install software stack
      continue-on-error: true
      run: |
        source setup.sh ""
      shell: bash