name: "Build images and test for multiple python versions"
on:
    push:
    workflow_dispatch:

jobs:
    do_all:
        strategy:
            fail-fast: false
            matrix: 
                # PYVERSION: ["3.9", "3.10"]
                PYVERSION: ["3.7", "3.8", "3.9", "3.10", "3.11"]
                FORCE_COMPILE_ENV: ["True"]
                include:
                    - PYVERSION: "3.7"
                      FORCE_COMPILE_ENV: "False"
                    - PYVERSION: "3.8"
                      FORCE_COMPILE_ENV: "False"
                    

        uses: ./.github/workflows/build_and_test_single.yaml
        secrets: inherit
        permissions:
            contents: read
            packages: write
        with:
            PYVERSION: ${{ matrix.PYVERSION }}
        name: "Build and test for Python ${{ matrix.PYVERSION }}"
