name: Build Docker Containers
on:
  # push:
  workflow_dispatch:
  workflow_call:
    inputs:
      PYVERSION: 
        description: "Python version to be used for build"
        required: false
        type: string
        default: "3.10"

jobs:
  parse_env_vars:
    runs-on: ubuntu-latest
    outputs:
      BASE_HASH_FILES: ${{ steps.file_manager.outputs.BASE_HASH_FILES }}
      BASE_FILE_HASH: ${{ steps.file_manager.outputs.BASE_FILE_HASH }}
      COLUMNAR_HASH_FILES: ${{ steps.file_manager.outputs.COLUMNAR_HASH_FILES }}
      COLUMNAR_FILE_HASH: ${{ steps.file_manager.outputs.COLUMNAR_FILE_HASH }}
      ML_TF_HASH_FILES: ${{ steps.file_manager.outputs.ML_TF_HASH_FILES }}
      ML_TF_FILE_HASH: ${{ steps.file_manager.outputs.ML_TF_FILE_HASH }}
      DOCS_HASH_FILES: ${{ steps.file_manager.outputs.DOCS_HASH_FILES }}
      DOCS_FILE_HASH: ${{ steps.file_manager.outputs.DOCS_FILE_HASH }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      with:
        lfs: true
    - uses: ./.github/actions/file_manager
      id: file_manager
      name: "initialize file manager"

  build_base_software:
    uses: ./.github/workflows/build_docker_container.yaml
    needs: [parse_env_vars]
    permissions:
      contents: read
      packages: write
    name: Build base software
    with:
      IMAGE_NAME: "software-base"
      PUSH_IMAGE: true
      PYVERSION: ${{ inputs.PYVERSION || 3.10 }}
      BUILD_ARGS: |
        exe_file=setup.sh
      HASHFILES: ${{ needs.parse_env_vars.outputs.BASE_HASH_FILES }}
      HASH: ${{ needs.parse_env_vars.outputs.BASE_FILE_HASH }}
      FORCE_PUSH_IMAGE: false
    secrets: inherit

  
  build_venvs:
    needs: [parse_env_vars,build_base_software]
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - venv: "columnar"
            name: "columnar"
            hashFiles: ${{ needs.parse_env_vars.outputs.COLUMNAR_HASH_FILES }}
            hash: ${{ needs.parse_env_vars.outputs.COLUMNAR_FILE_HASH }}
          - venv: ml_tf
            name: "ml_tf"
            hashFiles: ${{ needs.parse_env_vars.outputs.ML_TF_HASH_FILES }}
            hash: ${{ needs.parse_env_vars.outputs.ML_TF_FILE_HASH }}
          - venv: docs_dev
            name: "docs_dev"
            hashFiles: ${{ needs.parse_env_vars.outputs.DOCS_HASH_FILES }}
            hash: ${{ needs.parse_env_vars.outputs.DOCS_FILE_HASH }}
    uses: ./.github/workflows/build_docker_container.yaml
    with:
      IMAGE_NAME: venv_${{ matrix.name }}
      PUSH_IMAGE: true
      PYVERSION: ${{ inputs.PYVERSION || 3.10 }}
      BUILD_ARGS: |
        exe_file=sandboxes/venv_${{ matrix.venv }}.sh
        base=ghcr.io/${{ github.repository }}/software-base:python${{ inputs.PYVERSION || 3.10 }}-${{ needs.parse_env_vars.outputs.BASE_FILE_HASH }}
      HASHFILES: |
        ${{ needs.parse_env_vars.outputs.BASE_HASH_FILES }}
        ${{ matrix.hashFiles }}
      HASH: ${{ matrix.hash }}
    secrets: inherit
