name: Setup virtual environments
on: 
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        default: ubuntu-latest
  workflow_dispatch:
  workflow_run:
    workflows:
      - Setup basic software environment
    types:
      - completed

jobs:

  venv_matrix:
    runs-on: ubuntu-latest
    # env:
    #   CF_SOFTWARE_BASE: ./
    strategy:
      matrix:
        include:
          - venv: "columnar"
            name: "columnar"
            hashFiles: |
              **/sandboxes/venv_columnar*.sh
              **/sandboxes/columnar.txt
              **/sandboxes/_setup_venv.sh
          - venv: "docs"
            name: "docs"
            hashFiles: |
              **/sandboxes/venv_docs*.sh
              **/sandboxes/_setup_venv.sh
          - venv: ml_tf
            name: "ML (TensorFlow)"
            hashFiles: |
              **/sandboxes/_setup_venv.sh
              **/sandboxes/venv_ml_tf*.sh
              **/sandboxes/ml_tf.txt
    steps:
      - uses: actions/checkout@v3
      - id: "setup_basic_software"
        uses: ./.github/actions/setup_software
        with:
          cache-name: "cache-software-basis"
      - name: ${{ matrix.name }}
        uses: ./.github/actions/setup_software

        with:
          cache-name: "cache-${{ matrix.venv }}"
          run_additional: "./sandboxes/venv_${{ matrix.venv }}_dev.sh"
          cache_paths: |
            data/software/venvs/venv_${{ matrix.venv }}*
          filesForHash: |
            ${{ matrix.hashFiles }}
            setup.sh
