name: Setup software base

on:
  workflow_call:
    inputs:
        config-path:
          required: true
          type: string
    secrets:
      token:
        required: true

jobs:
  Setup_software_basis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@master
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies ☕️
        id: cache-software-basis
        uses: actions/cache@v3
        env:
          cache-name: cache-software-basis
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            GITHUB_WORKSPACE/columnflow/data/software/venvs/*
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('requirements*.txt', 'sandboxes/cf_*.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-software-basis.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: |
          source setup.sh ""