name: Setup basic software environment
on: 
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        default: ubuntu-latest
  workflow_dispatch:
  
    
    

jobs:

  setup-base:
    runs-on: ${{ inputs.os }}
    environment: Software Build
    steps:
      - uses: actions/checkout@v3
      - id: "setup_basic_software"
        uses: ./.github/actions/setup_software
        with:
          cache-name: "cache-software-basis"