name: Build Docker Container
on:
  push:
jobs:    
  build_base_software:
    runs-on: ubuntu-latest
    environment: Software Build
    secrets: inherit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
          clean: false
      - name: Build base software
        uses: ./.github/workflows/build_docker_container.yaml
        permissions:
          contents: read
          packages: write
        with:
          IMAGE_NAME: "software-base"
          PUSH_IMAGE: true
          PYVERSION: "3.10"
          BUILD_ARGS: |
            exe_file=setup.sh
          HASHFILES: |
            **/requirements*.txt
            **/sandboxes/cf_*.sh
            **/setup.sh
            **/_setup*.sh
            pyproject.toml
  
  build_venvs:
    runs-on: ubuntu-latest
    needs: build_base_software
    environment: Software Build
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - venv: "columnar"
            name: "columnar"
            hashFiles: |
              **/sandboxes/venv_columnar*.sh
              **/sandboxes/columnar.txt
              **/sandboxes/_setup_venv.sh
          - venv: ml_tf
            name: "ml_tf"
            hashFiles: |
              **/sandboxes/_setup_venv.sh
              **/sandboxes/venv_ml_tf*.sh
              **/sandboxes/ml_tf.txt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
          clean: false
      - name: ${{ matrix.name }}
        uses: ./.github/workflows/build_docker_container.yaml
        with:
          IMAGE_NAME: venv_${{ matrix.name }}
          PUSH_IMAGE: true
          PYVERSION: "3.10"
          BUILD_ARGS: |
            exe_file=sandboxes/venv_${{ matrix.venv }}.sh
            base=ghcr.io/${{ github.repository }}/software-base:latest
          HASHFILES: |
            **/requirements*.txt
            **/sandboxes/cf_*.sh
            **/setup.sh
            **/_setup*.sh
            pyproject.toml
            ${{ matrix.hashFiles }}
        # secrets: inherit
