on:
  push:
jobs:
  container-test:
    uses: ./.github/workflows/build_docker_container
    with:
      IMAGE_NAME: "software-base"
      PUSH_IMAGE: "true"
      BUILD_ARGS: |
        --build-arg pyversion='3.10'
        --build-arg exe_file=setup.sh
      HASHFILES: |
        **/requirements*.txt
        **/sandboxes/cf_*.sh
        **/setup.sh
        **/_setup*.sh
        pyproject.toml
    secrets: inherit