name: Build Docker Containers
on:
  # push:
  workflow_dispatch:
  push:

env:
  BASE_HASH_FILES: |
    **/requirements*.txt
    **/sandboxes/cf_*.sh
    **/setup.sh
    **/_setup*.sh
    pyproject.toml


jobs:
  parse_env_vars:
    runs-on: ubuntu-latest
    outputs:
      BASE_HASH_FILES: ${{ env.BASE_HASH_FILES }}
      BASE_FILE_HASH: ${{ steps.parse_env_vars.outputs.BASE_FILE_HASH }}
    steps:
      - name: Parse env vars
        id: parse_env_vars
        run: echo "BASE_FILE_HASH=${{ hashFiles(env.BASE_HASH_FILES) }}" >> $GITHUB_OUTPUT
        shell: bash
  build_base_software:
    uses: ./.github/workflows/build_docker_container.yaml
    needs: [parse_env_vars]
    permissions:
      contents: read
      packages: write
    name: Build base software
    with:
      IMAGE_NAME: "software-base"
      PUSH_IMAGE: true
      PYVERSION: "3.10"
      BUILD_ARGS: |
        exe_file=setup.sh
      HASHFILES: ${{ needs.parse_env_vars.outputs.BASE_HASH_FILES }}
    secrets: inherit

  
  build_venvs:
    needs: [parse_env_vars,build_base_software]
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - venv: "columnar"
            name: "columnar"
            hashFiles: |
              **/sandboxes/venv_columnar*.sh
              **/sandboxes/columnar.txt
              **/sandboxes/_setup_venv.sh
          - venv: ml_tf
            name: "ml_tf"
            hashFiles: |
              **/sandboxes/_setup_venv.sh
              **/sandboxes/venv_ml_tf*.sh
              **/sandboxes/ml_tf.txt
    uses: ./.github/workflows/build_docker_container.yaml
    with:
      IMAGE_NAME: venv_${{ matrix.name }}
      PUSH_IMAGE: true
      PYVERSION: "3.10"
      BUILD_ARGS: |
        exe_file=sandboxes/venv_${{ matrix.venv }}.sh
        base=ghcr.io/${{ github.repository }}/software-base:python3.10-${{ needs.parse_env_vars.outputs.BASE_FILE_HASH }}
      HASHFILES: |
        ${{ needs.parse_env_vars.outputs.BASE_HASH_FILES }}
        ${{ matrix.hashFiles }}
    secrets: inherit
