on:
  push:


jobs:
  container-test:
  - name: Checkout repository
      uses: actions/checkout@v4
  - name: Build Docker image
    uses: ./.github/actions/build_docker
    with:
      IMAGE_NAME: "software-base"
      PUSH_IMAGE: "true"
      BUILD_ARGS: |
        --build-arg pyversion='3.10'
        --build-arg exe_file=setup.sh
      HASHFILES: |
        **/requirements*.txt
        **/sandboxes/cf_*.sh
        **/setup.sh
        **/_setup*.sh
        pyproject.toml