name: Build Docker Container
on:
  push:
jobs:
  container-test:
    uses: ./.github/workflows/build_docker_container.yaml
    permissions:
      contents: read
      packages: write
    with:
      IMAGE_NAME: "software-base"
      PUSH_IMAGE: true
      PYVERSION: "3.10"
      BUILD_ARGS: |
        exe_file=setup.sh
      HASHFILES: |
        **/requirements*.txt
        **/sandboxes/cf_*.sh
        **/setup.sh
        **/_setup*.sh
        pyproject.toml
    secrets: inherit