name: Build Docker Containers
on:
  # push:
  workflow_dispatch:
  push:

jobs:
  parse_env_vars:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/file_manager
      name: "initialize file manager"
  build_base_software:
    uses: ./.github/workflows/build_docker_container.yaml
    needs: [parse_env_vars]
    permissions:
      contents: read
      packages: write
    name: Build base software
    with:
      IMAGE_NAME: "software-base"
      PUSH_IMAGE: true
      PYVERSION: "3.10"
      BUILD_ARGS: |
        exe_file=setup.sh
      HASHFILES: ${{ needs.parse_env_vars.outputs.BASE_HASH_FILES }}
    secrets: inherit

  
  build_venvs:
    needs: [parse_env_vars,build_base_software]
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - venv: "columnar"
            name: "columnar"
            hashFiles: ${{ needs.parse_env_vars.outputs.COLUMNAR_HASH_FILES }}
          - venv: ml_tf
            name: "ml_tf"
            hashFiles: ${{ needs.parse_env_vars.outputs.ML_TF_HASH_FILES }}
          - venv: docs_dev
            name: "docs_dev"
            hashFiles: ${{ needs.parse_env_vars.outputs.DOCS_HASH_FILES }}
    uses: ./.github/workflows/build_docker_container.yaml
    with:
      IMAGE_NAME: venv_${{ matrix.name }}
      PUSH_IMAGE: true
      PYVERSION: "3.10"
      BUILD_ARGS: |
        exe_file=sandboxes/venv_${{ matrix.venv }}.sh
        base=ghcr.io/${{ github.repository }}/software-base:python3.10-${{ needs.parse_env_vars.outputs.BASE_FILE_HASH }}
      HASHFILES: |
        ${{ needs.parse_env_vars.outputs.BASE_HASH_FILES }}
        ${{ matrix.hashFiles }}
    secrets: inherit
